### ISSUE TITLE
Request for setup instructions

### ISSUE THREAD

**Issue by Jovian-Dsouza** [luc-github/Flashair-FM#6]
Could you please provide how to set this up for ESP 3D 2.1 . Sorry I am a bit confused regarding how to use this. Will this make SD printing faster

**Comment by luc-github** [comment]
currently there is no ESP3D 2.1 `native` SD Flash air integration - in 3.0 I am still thinking how to do, because Flash air does not allow direct ajax commands
Currently the easy way is to use the webUI camera panel - so you enter the ip address of the flash air in preferences and the Flah air will show in camera panel

Here the open ticket FYR : https://github.com/luc-github/ESP3D-WEBUI/issues/19, I will find a solution in 3.0 as I also definitly need it ^_^

**Comment by luc-github** [comment]
@Jovian-Dsouza did this answered your question ?

**Comment by Jovian-Dsouza** [comment]
> @Jovian-Dsouza did this answered your question ?

Yes , Thank you , Let me know how I can help in implementing this feature for 3.0
